In [2]:
using FFTW
using PaddedViews
using DSP
using LinearAlgebra
using Random
using Zygote

function validconv(u,g)
    nu = size(u)[1]
    ng = size(g)[1]
    out = conv(u,g)[nu+1:ng,nu+1:ng]

end

function validconvfft(u,g)

    nu = size(u)[1]
    ng = size(g)[1]
    uu = PaddedView(0,u,(nu+ng-1,nu+ng-1))
    gg = PaddedView(0,g,(ng+nu-1,nu+ng-1))
    out = real.(ifft(fft(gg).*fft(uu)))[nu+1:ng,nu+1:ng]

end

function validconvfft2(u,g)

    nu = size(u)[1]
    ng = size(g)[1]
    nv = ng - nu
    i1 = 1+(nu÷2)
    i2 = i1 + nv -1
    uu = collect(sym_paddedviews(0,u,g)[1]) 
    out = real.(ifftshift(ifft(fft(g).*fft(uu))))[i1:i2,i1:i2]

end
nu,ng=10,30
u = rand(nu,nu)
g = rand(ng,ng)
display(validconv(u,g))
display(validconvfft(u,g))
display(validconvfft2(u,g))

20×20 Matrix{Float64}:
 26.7812  26.488   28.0306  26.0965  …  23.9443  22.2589  24.3153  21.8602
 26.3796  26.151   27.7268  29.0444     23.9356  21.7662  23.0994  25.3098
 23.335   26.2227  26.8282  24.2794     24.1271  24.8123  23.575   24.8784
 25.351   25.6345  26.8454  26.3872     23.9353  24.6334  23.6297  24.0506
 24.0542  26.5028  23.4783  24.3369     22.125   25.0654  23.9724  25.2736
 25.0252  25.095   25.0417  22.2577  …  24.6397  23.9663  26.9445  25.1232
 24.9139  25.2086  24.15    23.1651     23.643   23.6952  24.8405  24.0525
 24.218   24.7215  24.8003  23.7141     24.7688  23.0965  24.4946  23.8169
 23.894   22.1579  23.9436  23.0545     23.3152  24.4641  23.8827  23.3464
 22.1919  24.0361  23.7216  22.7459     25.7252  25.9698  26.3939  23.428
 24.6779  24.4163  24.0067  22.0651  …  23.6565  23.4368  24.4636  24.8444
 25.289   25.4209  23.2081  22.5427     25.3505  23.4575  25.7714  23.7184
 24.1567  24.3969  23.8022  23.772      24.2526  25.3272  24.9558  22.9988
 23

20×20 Matrix{Float64}:
 26.7812  26.488   28.0306  26.0965  …  23.9443  22.2589  24.3153  21.8602
 26.3796  26.151   27.7268  29.0444     23.9356  21.7662  23.0994  25.3098
 23.335   26.2227  26.8282  24.2794     24.1271  24.8123  23.575   24.8784
 25.351   25.6345  26.8454  26.3872     23.9353  24.6334  23.6297  24.0506
 24.0542  26.5028  23.4783  24.3369     22.125   25.0654  23.9724  25.2736
 25.0252  25.095   25.0417  22.2577  …  24.6397  23.9663  26.9445  25.1232
 24.9139  25.2086  24.15    23.1651     23.643   23.6952  24.8405  24.0525
 24.218   24.7215  24.8003  23.7141     24.7688  23.0965  24.4946  23.8169
 23.894   22.1579  23.9436  23.0545     23.3152  24.4641  23.8827  23.3464
 22.1919  24.0361  23.7216  22.7459     25.7252  25.9698  26.3939  23.428
 24.6779  24.4163  24.0067  22.0651  …  23.6565  23.4368  24.4636  24.8444
 25.289   25.4209  23.2081  22.5427     25.3505  23.4575  25.7714  23.7184
 24.1567  24.3969  23.8022  23.772      24.2526  25.3272  24.9558  22.9988
 23

20×20 Matrix{Float64}:
 26.7812  26.488   28.0306  26.0965  …  23.9443  22.2589  24.3153  21.8602
 26.3796  26.151   27.7268  29.0444     23.9356  21.7662  23.0994  25.3098
 23.335   26.2227  26.8282  24.2794     24.1271  24.8123  23.575   24.8784
 25.351   25.6345  26.8454  26.3872     23.9353  24.6334  23.6297  24.0506
 24.0542  26.5028  23.4783  24.3369     22.125   25.0654  23.9724  25.2736
 25.0252  25.095   25.0417  22.2577  …  24.6397  23.9663  26.9445  25.1232
 24.9139  25.2086  24.15    23.1651     23.643   23.6952  24.8405  24.0525
 24.218   24.7215  24.8003  23.7141     24.7688  23.0965  24.4946  23.8169
 23.894   22.1579  23.9436  23.0545     23.3152  24.4641  23.8827  23.3464
 22.1919  24.0361  23.7216  22.7459     25.7252  25.9698  26.3939  23.428
 24.6779  24.4163  24.0067  22.0651  …  23.6565  23.4368  24.4636  24.8444
 25.289   25.4209  23.2081  22.5427     25.3505  23.4575  25.7714  23.7184
 24.1567  24.3969  23.8022  23.772      24.2526  25.3272  24.9558  22.9988
 23

In [78]:
using FiniteDifferences
using BenchmarkTools
function vgu(g,u,v)

    nu = size(u)[1]
    ng = size(g)[1]
    out = conv(u,g)[nu+1:ng,nu+1:ng]

    sum(v .* out)

end

function v∂gu(g,u,v)

    nu = size(u)[1]
    nv = size(v)[1]
    uu = collect(sym_paddedviews(0,u,g)[1])
    vv = collect(sym_paddedviews(0,v,g)[1])
    real.( ifftshift( ifft( fft(vv) .* conj.(fft(uu)) ) ))

end

function vGTGu(g,u,v)

    nu = size(u)[1]
    ng = size(g)[1]
    Gu = conv(u,g)[nu+1:ng,nu+1:ng]
    Gv = conv(v,g)[nu+1:ng,nu+1:ng]

    sum(Gv .* Gu)

end

function v∂GTGu(g,u,v)

    narr = size(u)[1]
    ng = size(g)[1]
    nout = ng - narr
    i1 = 1+(narr÷2)
    i2 = i1 + nout -1
    uu = collect(sym_paddedviews(0,u,g)[1]) 
    vv = collect(sym_paddedviews(0,v,g)[1])
    Gu = real.(ifftshift(ifft(fft(g).*fft(uu))))[i1:i2,i1:i2]
    Gv = real.(ifftshift(ifft(fft(g).*fft(vv))))[i1:i2,i1:i2]

    v∂gu(g,u,Gv) .+ v∂gu(g,v,Gu)

end

# nu,ng=10,26
# nv=ng-nu
# u = rand(nu,nu)
# g = rand(ng,ng)
# v = rand(nv,nv)
# gdat = grad(central_fdm(5,1), x->vgu(x,u,v), g)[1]
# gdat1 = v∂gu(g,u,v)
# display(maximum(abs.(gdat .- gdat1))/mean(abs.(gdat)))

nu,ng=6,12
nv=nu
u = rand(nu,nu)
g = rand(ng,ng)
v = rand(nv,nv)
gdat = grad(central_fdm(5,1), x->vGTGu(x,u,v), g)[1]
gdat1 = v∂GTGu(g,u,v)
display(maximum(abs.(gdat .- gdat1))/mean(abs.(gdat)))

2.695092745816874e-12

In [117]:
using Base.Threads
using FiniteDifferences
using BenchmarkTools

function vGTGu(g,u,v)

    nu = size(u)[1]
    ng = size(g)[1]
    m = size(g)[3]
    Gu = zeros(Float64,ng-nu,ng-nu)
    Gv = zeros(Float64,ng-nu,ng-nu)
    for i in 1:m
        @views Gu[:,:] .+= conv(u[:,:,i],g[:,:,i])[nu+1:ng,nu+1:ng]
        @views Gv[:,:] .+= conv(v[:,:,i],g[:,:,i])[nu+1:ng,nu+1:ng]
    end

    sum(Gv .* Gu)

end

function v∂gu(g,u,v)

    uu = collect(sym_paddedviews(0,u,g)[1])
    vv = collect(sym_paddedviews(0,v,g)[1])
    real.( ifftshift( ifft( fft(vv) .* conj.(fft(uu)) ) ))

end

function v∂GTGu(g,u,v)

    narr = size(u)[1]
    ng = size(g)[1]
    nfreqs = size(g)[3]
    nout = ng - narr
    i1 = 1+(narr÷2)
    i2 = i1 + nout -1
    Gu = zeros(Float64,nout,nout)
    Gv = zeros(Float64,nout,nout)
    Threads.@threads for i in 1:nfreqs
        uu = collect(sym_paddedviews(0,u[:,:,i],g[:,:,i])[1]) 
        vv = collect(sym_paddedviews(0,v[:,:,i],g[:,:,i])[1])
        @views Gu[:,:] .+= real.(ifftshift(ifft(fft(g[:,:,i]).*fft(uu))))[i1:i2,i1:i2]
        @views Gv[:,:] .+= real.(ifftshift(ifft(fft(g[:,:,i]).*fft(vv))))[i1:i2,i1:i2]
    end

    ∂g = zeros(Float64,ng,ng,nfreqs)
    Threads.@threads for i in 1:nfreqs
        @views ∂g[:,:,i] .= v∂gu(g[:,:,i],u[:,:,i],Gv) .+ v∂gu(g[:,:,i],v[:,:,i],Gu)
    end

    ∂g

end

using Random

Random.seed!(3)
nu = 14
ng = 16
nfreqs = 5
g = rand(Float64,ng,ng,nfreqs)
u = rand(Float64,nu,nu,nfreqs)
v = rand(Float64,nu,nu,nfreqs)

gdat = grad(central_fdm(5,1), x->vGTGu(x,u,v), g)[1]
gdat1 = v∂GTGu(g,u,v)
display(maximum(abs.(gdat .- gdat1))/mean(abs.(gdat)))

1.881593789881613e-11

In [128]:
n=4
p = plan_rfft(rand(Float64,n,n),flags=FFTW.MEASURE)
p \ (p * rand(Float64,n,n))

4×4 Matrix{Float64}:
 0.331889   0.792513  0.528247  0.313269
 0.528449   0.395595  0.500903  0.21754
 0.903764   0.237026  0.854022  0.838578
 0.0630948  0.472075  0.314593  0.3439