In [1]:
include("./End2End.jl")
using .End2End
using FiniteDifferences

ncells = 6
lb = 0.11
ub = 0.68
F,∂F,params = setup(lb=0.11,ub=0.68,
                    filename="alldat_5wavs.dat",
                    ncells=ncells,
                    npix=4,nintg=2,
                    ntruth=2,
                    nthr=1,
                    freqs=[0.8,1.0,1.2],
                    δx = 0.8, δy = 0.8,
                    Dz = 500.0,
                    ϵ_free = 1.0, μ_free = 1.0,
                    ntrain = 4,
                    α = 100.0);
p₀ = rand(1.2*lb:0.01/ncells^2:0.8*ub,ncells^2)
gdat = zeros(ncells*ncells)
tmp = zeros(ncells*ncells)
end2end!(gdat, F,∂F, params.models, p₀, F2ℓ, params);
# gdat1 = grad(central_fdm(5,1), x->end2end!(tmp, F,∂F, params.models, x, F2ℓ, params), p₀)[1]
# display(maximum(abs.(gdat .- gdat1))/mean(abs.(gdat)))

    Updating registry at `C:\Users\zinli\.julia\registries\General.toml`
   Resolving package versions...
  No Changes to `C:\Users\zinli\.julia\environments\v1.8\Project.toml`
  No Changes to `C:\Users\zinli\.julia\environments\v1.8\Manifest.toml`
   Resolving package versions...
  No Changes to `C:\Users\zinli\.julia\environments\v1.8\Project.toml`
  No Changes to `C:\Users\zinli\.julia\environments\v1.8\Manifest.toml`
   Resolving package versions...
  No Changes to `C:\Users\zinli\.julia\environments\v1.8\Project.toml`
  No Changes to `C:\Users\zinli\.julia\environments\v1.8\Manifest.toml`
   Resolving package versions...
  No Changes to `C:\Users\zinli\.julia\environments\v1.8\Project.toml`
  No Changes to `C:\Users\zinli\.julia\environments\v1.8\Manifest.toml`
   Resolving package versions...
  No Changes to `C:\Users\zinli\.julia\environments\v1.8\Project.toml`
  No Changes to `C:\Users\zinli\.julia\environments\v1.8\Manifest.toml`
   Resolving package versions...
  No Changes t

Performing FFP for freq 1
Performing FFP for freq 2Performing FFP for freq 3

Evaluating the transmission coefficients
Performing FFP for freq 1
Performing FFP for freq 2
Performing FFP for freq 3
Reconstruction stage: ground truth 4
Reconstruction stage: ground truth 1
Reconstruction stage: ground truth 3
Reconstruction stage: ground truth 2
CG converged in 3 steps with residual 1.2489141463710478e-39.
CG converged in 3 steps with residual 5.656515783482335e-42.
CG converged in 3 steps with residual 1.6170433644866102e-40.
CG converged in 3 steps with residual 2.1673165186999433e-41.
  0.036478 seconds (8.34 k allocations: 1001.812 KiB)
  0.037160 seconds (9.27 k allocations: 1.074 MiB)
  0.038058 seconds (10.02 k allocations: 1.152 MiB)
  0.037366 seconds (9.29 k allocations: 1.069 MiB)
Backpropagation stage: ground truth 1
Backpropagation stage: ground truth 2
Backpropagation stage: ground truth 3
Backpropagation stage: ground truth 4
CG converged in 3 steps with residual 3.34495841

In [4]:
a = [0,-1,-2,4,1,1]
display(a)
a[a.<0].=1
display(a)

6-element Vector{Int64}:
  0
 -1
 -2
  4
  1
  1

6-element Vector{Int64}:
 0
 1
 1
 4
 1
 1

In [6]:
using BenchmarkTools
a = rand(3,3)
mean(a)

0.5209283247529888

In [1]:
using IterativeSolvers
tmp = rand(100,100) 
A = tmp + tmp'
b = rand(100)
x,ch = cg(A,b,maxiter=10000,abstol=10^(-16),reltol=10^(-16),log=true)

([-0.38409850654038313, 1.1856206294084377, 0.9020283584305085, -0.8112994729356016, 1.7267661167391894, -0.8507440087003972, -0.4248703803690912, -0.8751495491563163, -0.1954549592209788, 0.04083380131078818  …  -0.22578348525618944, -0.82300201257497, -0.9728372138131716, 1.5508594415004513, 2.176090136297172, -0.0962309220730193, 1.0362581824195334, 2.1193914632986837, 0.08306418015270747, 1.0942304496887438], Converged after 333 iterations.)

In [2]:
x

100-element Vector{Float64}:
 -0.38409850654038313
  1.1856206294084377
  0.9020283584305085
 -0.8112994729356016
  1.7267661167391894
 -0.8507440087003972
 -0.4248703803690912
 -0.8751495491563163
 -0.1954549592209788
  0.04083380131078818
 -1.2488180219900082
 -1.4075722807586377
  1.38098143651682
  ⋮
 -0.7780311665807988
  0.3022777516617916
 -0.22578348525618944
 -0.82300201257497
 -0.9728372138131716
  1.5508594415004513
  2.176090136297172
 -0.0962309220730193
  1.0362581824195334
  2.1193914632986837
  0.08306418015270747
  1.0942304496887438

In [25]:
println("here $(size(ch[:resnorm],1))")

here 346


In [9]:
a = rand(4,4)
b = rand(4,4)
c = rand(4,4)
a .= b .- c

4×4 Matrix{Float64}:
 -0.0424977   0.343029   -0.190162   0.412104
  0.0965815  -0.535015    0.361012   0.0556645
  0.135794    0.494206   -0.172699  -0.226906
 -0.415337   -0.0028238   0.260202   0.766378

In [8]:
a

4×4 Matrix{Float64}:
 -0.0382015  -0.562033   0.0384774   0.386995
 -0.0561613  -0.913631   0.739032   -0.299498
  0.0944967   0.18209    0.208503    0.0678999
  0.334125   -0.473607  -0.388278   -0.0382952

In [11]:
a=rand(4,4,3)
size(vec(a),1)

48

In [13]:
using LinearAlgebra
dot(a,a)

15.54510044380559